//
// Created by eric1 on 6/13/2024.
//

#ifndef DESIGN_PATTERNS_EXAMPLES_POINTTYPE_H
#define DESIGN_PATTERNS_EXAMPLES_POINTTYPE_H

enum class PointType {
    HOSPITAL,
    CAFE,
    RESTAURANT,
};

#endif //DESIGN_PATTERNS_EXAMPLES_POINTTYPE_H
